### ISSUE TITLE
Issues with Videotel (Italian Minitel)

### ISSUE THREAD

**Issue by r00li** [jbellue/3615_SSH#1] opened 2022-10-25 19:07 UTC
Hi!
I recently got my hands on an Italian version of Minitel called Videotel. Sadly I can't find any technical documentation on them, but from what I see they should generally be compatible. Sadly it seems like there are some issues...

When running this without any modifications I get this on screen and that's it:
![IMG_5928](https://user-images.githubusercontent.com/2136711/197857952-831e0984-faa6-4087-b9d5-d5ace1fee063.jpg)

These are my connection settings:
![IMG_5929](https://user-images.githubusercontent.com/2136711/197858200-a70bb35b-0064-421d-92bd-4abcb7eaa15a.jpg)

With some small investigation I found out that it seems to hang on the `minitel->smallMode();` line in main.cpp. If I remove this line I get the splash screen image. I can then get into the wifi setup menu and everything. In this menu (and SSH connect menu), whatever I type doesn't show up on screen. For example when typing in a wifi password only the first * shows up and nothing more. The input is however detected properly. Except that it is in caps and I need to hold shift to get lower case letters. But I could get it connected to wifi just fine and this part seems to work fine.

Do you have any ideas what might be different and why this isn't working as it should be?

**Comment by jbellue** [comment] 2022-11-09 15:58
Hi!
I'm sorry, I have no clue what the issue could be... The French minitel doesn't have that connection screen, so I reckon the software is pretty different.
`smallMode` puts the minitel in lower case, so you don't need to press Shift to get the lower case characters.
If you can find the docs for that minitel, surely we can figure out what the issue is, but without that, I'm afraid there's nothing I could do.

I reckon with an awful lot of trial and error, you could potentially figure out the protocol, but it would probably be a real pain.

Sorry!

**Comment by jbellue** [comment] 2022-11-09 16:04
Maybe you can try with these different combinations just on startup:
    Funz + Mem: Switches to terminal mode
    Funz + M A: Enables ASCII mode
    Funz + M E: Disables local echo
    Funz + B 4: Sets baud rate to 4800 Baud (the maximum)

**Comment by r00li** [comment] 2022-11-21 20:08
Hey! After some playing around I have actually figured out most of it. And I can now use it to SSH to my computer and it works pretty well. I had to modify the Minitel1B_Hard.cpp and in functions like `workingMode`, `workingStandard`, ... just return 0 instead of actually waiting for the videotel to respond. For example switching modes, switching to small characters, ... all of it works fine. It's just that videotel doesn't seem to respond anything. The only issue left seem to be the function keys, which wheen pressed seem to freeze everything. But luckily they don't seem to be needed. 

The other slightly problematic page was sshPage, since it needed some mods for the cursor handling. Looks like `moveCursorXY` doesn't seem to work quite right (while moveCursror down/up/left/right work fine). But I managed to 'hack' it together so it works decently enough now. 

I think these are like 99% compatible with minitel, but it's hard to figure out anything because there just isn't any technical information available on them.

**Comment by jbellue** [comment] 2022-11-22 08:57
It would be nice to get the documentation, to support the Videotel in Minitel1B_Hard.cpp.
Maybe you can open an issue on https://github.com/eserandour/Minitel1B_Hard so they can have a look and potentially add some support.
I'm closing this issue now, I'm glad you got it working!

**Closed as completed by jbellue** 2022-11-22 08:57 UTC
